/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import assets from '../utils/assets'

const Fountain = ({ ...props }) => {
  const group = useRef()
  const { nodes, materials } = useGLTF(assets('/models/fountain.glb'))
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Mesh_Mesh_head_geo001_lambert2SG001.geometry} material={materials['lambert2SG.001']} />
      </group>
    </group>
  )
}

export default Fountain

useGLTF.preload(assets('/models/fountain.glb'))
